version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/index.html:/var/www/html/index.html
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build: ./app
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    expose:
      - 3306